Import plainbox-provider-checkbox_0.50.0~rc1.orig.tar.gz

diff --git a/providers/checkbox-packaging/bin/disk_read_performance_test b/providers/checkbox-packaging/bin/disk_read_performance_test
--- a/providers/checkbox-packaging/bin/disk_read_performance_test
+++ b/providers/checkbox-packaging/bin/disk_read_performance_test
@@ -13,6 +13,19 @@ for disk in $@; do
 
   disk_type=`udevadm info --name /dev/$disk --query property | grep "ID_BUS" | awk '{gsub(/ID_BUS=/," ")}{printf $1}'`
   dev_path=`udevadm info --name /dev/$disk --query property | grep "DEVPATH" | awk '{gsub(/DEVPATH=/," ")}{printf $1}'`
+  if [[ $dev_path =~ dm ]]; then
+    disk_type="devmapper"
+  fi
+  if [[ $dev_path =~ nvme ]]; then
+    disk_type="nvme"
+  fi
+  if [[ $dev_path =~ mmc ]]; then
+    disk_type="mmc"
+  fi
+  if [ -z "$disk_type" ]; then
+  echo "ERROR: disk type not recognized"
+    exit 1
+  fi
   echo "INFO: $disk type is $disk_type"
 
   case $disk_type in
@@ -29,7 +42,10 @@ for disk in $@; do
                 fi
             fi
             ;;
+    "devmapper" ) MIN_BUF_READ=$DEFAULT_BUF_READ;;
     "ide" ) MIN_BUF_READ=40;;
+    "mmc" ) MIN_BUF_READ=$DEFAULT_BUF_READ;;
+    "nvme" ) MIN_BUF_READ=400;;
     *     ) MIN_BUF_READ=$DEFAULT_BUF_READ;;
   esac
   echo "INFO: $disk_type: Using $MIN_BUF_READ MB/sec as the minimum throughput speed"
@@ -45,7 +61,7 @@ for disk in $@; do
 
     if [ -z "$speed" ]; then
       echo "WARNING: Device $disk is too small! Aborting test."
-      exit 0
+      exit 1
     fi
 
     speed=${speed/.*}
