Import plainbox-provider-checkbox_0.21.orig.tar.gz

diff --git a/providers/checkbox-packaging/jobs/miscellanea.txt.in b/providers/checkbox-packaging/jobs/miscellanea.txt.in
--- a/providers/checkbox-packaging/jobs/miscellanea.txt.in
+++ b/providers/checkbox-packaging/jobs/miscellanea.txt.in
@@ -71,6 +71,52 @@ _description:
  This will run some basic connectivity tests against a BMC, verifying that IPMI works.
 
 plugin: shell
+estimated_duration: 0.5
+id: miscellanea/boot_mode
+_summary: EFI-mode boot test
+_description: Succeeds when booted in EFI mode; fails otherwise
+command:
+  if [ -d "/sys/firmware/efi" ] ; then
+    echo "System booted in EFI mode"
+  else
+    echo "System did NOT boot in EFI mode"
+    exit 1
+  fi
+
+plugin: shell
+id: miscellanea/bmc_info
+requires: package.name == 'ipmitool'
+estimated_duration: 0.5
+user: root
+command: bmc_info
+_description:
+ This will gather some info about the BMC itself for diagnostic purposes.
+_summary:
+ Gather BMC Identification info
+
+plugin: shell
+id: miscellanea/dmitest_server
+requires: package.name == 'dmidecode'
+estimated_duration: 0.5
+user: root
+command: dmitest --test_versions --test_serials server
+_description:
+ Sanity check of DMI system identification data (for servers)
+_summary:
+ DMI ID sanity check (servers)
+
+plugin: shell
+id: miscellanea/dmitest_client
+requires: package.name == 'dmidecode'
+estimated_duration: 0.5
+user: root
+command: dmitest --test_versions --test_serials desktop
+_description:
+ Sanity check of DMI system identification data (for desktops & laptops)
+_summary:
+ DMI ID sanity check (desktops/laptops)
+
+plugin: shell
 id: miscellanea/is_laptop
 user: root
 _description:
@@ -90,6 +136,7 @@ command: sources_test $SOURCES_LIST "$REPOSITORIES"
 _description: Checks that a specified sources list file contains the requested repositories
 
 plugin: local
+_summary: Automated job to generate the PXE verification test for each NIC.
 id: miscellanea/pxe_boot
 requires: device.category == 'NETWORK'
 _description: Automated job to generate the PXE verification test for each NIC.
@@ -110,6 +157,7 @@ command:
  EOF
 
 plugin: local
+_summary: Automated job to generate the Remote Shared IPMI verification test for each NIC.
 id: miscellanea/remote_shared_ipmi
 requires: device.category == 'NETWORK'
 _description: Automated job to generate the Remote Shared IPMI verification test for each NIC.
@@ -139,3 +187,43 @@ _description:
   Skip this test if this system ONLY uses shared management/ethernet ports OR if this system does not have a BMC (Management Console)
   1. Select Yes if you successfully used IPMI to remotely power this system off and on using the dedicated management port.
   2. Select No if you attempted to use the dedicated management port to remotely power this system off/on and it failed for some reason.
+
+plugin:shell
+id: miscellanea/oops
+estimated_duration: 10.0
+requires:
+  package.name == 'fwts'
+user: root
+_description:
+ Run Firmware Test Suite (fwts) oops tests.
+environ: PLAINBOX_SESSION_SHARE
+command:
+ fwts_test -l $PLAINBOX_SESSION_SHARE/fwts_oops_results.log -t oops
+
+plugin: attachment
+estimated_duration: 0.5
+id: miscellanea/oops_results.log
+command:
+ [ -e ${PLAINBOX_SESSION_SHARE}/fwts_oops_results.log ] && cat ${PLAINBOX_SESSION_SHARE}/fwts_oops_results.log
+_description: Attaches the FWTS oops results log to the submission
+
+plugin: shell
+estimated_duration: 0.1
+id: miscellanea/get_maas_version
+command:
+ if [ -s /etc/installed-by-maas ]; then 
+   cat /etc/installed-by-maas
+ else
+   echo "MAAS VERSION NOT FOUND" >&2
+   false
+ fi
+_description: If system was installed via MAAS from a cert server, the MAAS version used should be contained in /etc/installed-by-maas
+_summary: Gets the version of MAAS used to deploy the SUT
+
+plugin: shell
+estimated_duration: 30.0
+id: miscellanea/get_make_and_model
+user: root
+command: get_make_and_model
+_description: Retrieve the computer's make and model for easier access than digging through the dmidecode output.
+_summary: Retrieve the computer's make and model
